### ISSUE TITLE
Is there a effective way to locate the code address I want to hook?

### ISSUE THREAD

**Issue by serephus** [aers/SprintJumpSSE#2]
Say I want to make some changes to Skyrim's  camera or jump handler like this, something very specific, how can I locate the address of the code in the first place?
PS: Sorry,  I know I shouldn't post something like this in here, but I don't know anywhere else.

**Comment by aers** [comment]
![jtxrvzo](https://user-images.githubusercontent.com/1631648/41765923-5aee7518-75ba-11e8-9396-7b7d32652184.png)

IDA will tell you class names for the handlers since they have RTTI/vfuncs. Then you just have to use static analysis & a debugger on the function you care about to figure out what it does.

Camera code is a bit more complicated but SKSE has some stuff in GameCamera.

**Comment by serephus** [comment]
@aers 
Thanks a lot
